image: cirrusci/flutter:latest

before_script:
  - flutter pub global activate junitreport && export PATH="$PATH":"$HOME/.pub-cache/bin"

stages:
  - test

integration_test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  before_script:
    # Install Android SDK
    - pushd /opt
    - apt-get update     && apt-get install -y openjdk-11-jdk     && apt-get install -y sudo wget zip unzip git openssh-client curl bc software-properties-common build-essential ruby-full ruby-bundler libstdc++6 libpulse0 libglu1-mesa locales lcov libsqlite3-0 --no-install-recommends     && apt-get install -y libxtst6 libnss3-dev libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0     && rm -rf /var/lib/apt/lists/*     && sh -c 'echo "en_US.UTF-8 UTF-8" > /etc/locale.gen'     && locale-gen     && update-locale LANG=en_US.UTF-8     && wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip     && mkdir -p /opt/android-sdk-linux/cmdline-tools/     && unzip -q android-sdk-tools.zip -d /opt/android-sdk-linux/cmdline-tools/     && mv /opt/android-sdk-linux/cmdline-tools/cmdline-tools /opt/android-sdk-linux/cmdline-tools/latest     && chown -R root:root /opt/android-sdk-linux     && rm android-sdk-tools.zip     && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers     && yes | sdkmanager --licenses     && wget -O /usr/bin/android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator     && chmod +x /usr/bin/android-wait-for-emulator     && touch /root/.android/repositories.cfg     && sdkmanager platform-tools     && mkdir -p /root/.android     && touch /root/.android/repositories.cfg     && git config --global user.email "support@cirruslabs.org"     && git config --global user.name "Cirrus CI"
    - popd

    # pub get is required to generate the plugin java classes
    - flutter pub get

  script:
    # deploy to gcloud and run instrumented test
    - flutter clean
