name: interview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  built_value: ^8.1.2
  built_collection: ^5.1.1
  http: ^0.13.4
  flutter:
    sdk: flutter
  get_it: 7.2.0
  provider: 6.0.2
  readmore: ^2.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  built_value_generator: ^8.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
